# Generated by Django 6.0.3 on 2026-07-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
