# Generated by Django 6.0.3 on 2026-07-05 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_phone_alter_profile_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit phone number.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a valid 6-digit PIN code.')]),
        ),
    ]
