# Generated by Django 6.0.3 on 2026-07-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Prescription', 'verbose_name_plural': 'Prescriptions'},
        ),
        migrations.AlterModelOptions(
            name='prescriptionmedicine',
            options={'ordering': ['name'], 'verbose_name': 'Prescribed Medicine', 'verbose_name_plural': 'Prescribed Medicines'},
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='notes',
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='instructions',
            field=models.TextField(blank=True, help_text='e.g. After food'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='advice',
            field=models.TextField(blank=True, help_text='General advice for the patient.'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(help_text='Diagnosis made by the doctor.'),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='dosage',
            field=models.CharField(help_text='e.g. 500mg', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='duration',
            field=models.CharField(help_text='e.g. 5 days', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='frequency',
            field=models.CharField(help_text='e.g. Twice a day', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
