# Generated by Django 6.0.3 on 2026-07-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0002_remove_doctorslot_is_booked_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_slot_per_day',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('slot', 'appointment_date', 'appointment_time'), name='unique_slot_time_per_day'),
        ),
    ]
