service: mini-hms-email-service

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: python3.11
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 15

  environment:
    SMTP_HOST: ${env:SMTP_HOST}
    SMTP_PORT: ${env:SMTP_PORT}
    SMTP_USER: ${env:SMTP_USER}
    SMTP_PASSWORD: ${env:SMTP_PASSWORD}
    FROM_EMAIL: ${env:FROM_EMAIL}

package:
  patterns:
    - '!node_modules/**'
    - '!.git/**'
    - '!venv/**'
    - 'templates/**'

functions:
  sendEmail:
    handler: handler.send_email_handler
    events:
      - httpApi:
          path: /send-email
          method: post

plugins:
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: false
    slim: true

  serverless-offline:
    httpPort: 4000