# Generated by Django 6.0.3 on 2026-07-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorslot',
            name='is_booked',
        ),
        migrations.RemoveField(
            model_name='doctorslot',
            name='max_patients',
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='buffer_duration',
            field=models.PositiveIntegerField(default=5, help_text='Buffer time between appointments.'),
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='consultation_duration',
            field=models.PositiveIntegerField(default=10, help_text='Consultation duration in minutes.'),
        ),
    ]
